# Generated by Django 5.2.6 on 2025-10-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'USER'), (1, 'AUTHOR'), (2, 'ADMIN')], default=0),
        ),
    ]
